version: "3"

services:
  db:
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_sequelize
    ports:
      - "3308:3306"

  web:
    image: sequelize-docker
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    command: ["./wait-for-it.sh", "-t", "60", "db:3306", "--", "npm", "start"]
